name: BuildBattle
version: 2.0.0-N
author: SpopovabgS
api: [3.0.0-ALPHA11]
main: BuildBattle\Main
commands:
 join:
    description: Join a random BuildBattle match.
 bb:
    description: BuildBattle setup command.
